export const MULTIPLY = "COUNTER-DEMO/MULTIPLY"
export const SUBTRACT = "COUNTER-DEMO/SUBTRACT"
export const PLUS = "COUNTER-DEMO/PLUS"
export const DIVIDE = "COUNTER-DEMO/DIVIDE"
export const PLUS_FIRST_THEN_MULTIPLY = "COUNTER-DEMO/PLUS_FIRST_THEN_MULTIPLY"
export const PLUS_FIRST_THEN_DIVIDE_BY_TEN =
  "COUNTER-DEMO/PLUS_FIRST_THEN_DIVIDE_BY_TEN"
